services:
  postgres:
    image: postgres:15-alpine
    restart: no
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_DB=data
    volumes:
      - 01-sqlalchemy-core-postgres:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: no
    ports:
      - 127.0.0.1:8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWOED=pgadmin
    volumes:
      - 01-sqlalchemy-core-pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  01-sqlalchemy-core-pgadmin:
  01-sqlalchemy-core-postgres:
