name: sqlalchemy-orm-test

services:

  postgres:
    image: postgres:16-alpine
    # поскольку это тестовый стенд, то не перезагружаем автоматически
    restart: no
    ports:
      - 127.0.0.1:5432:5432
    environment:
      # логин и пароль первого (супер)пользователя, а также название БД
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_DB=data_for_bot
    volumes:
      - sqlalchemy-orm-test-postgres:/var/lib/postgresql/data_for_bot

  pgadmin:
    image: dpage/pgadmin4:8.9
    # поскольку это тестовый стенд, то не перезагружаем автоматически
    restart: no
    ports:
      - 127.0.0.1:8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - sqlalchemy-orm-test-pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  sqlalchemy-orm-test-postgres:
  sqlalchemy-orm-test-pgadmin:
