services:
  nats:
    image: nats
    entrypoint: /nats-server # Команда запуска серевера внутри контейнера
    ports:
      - 4222:4222 # Основной порт для взаимодействия с сервером
      - 8222:8222 # Порт для мониторинга сервера по HTTP (понадобится позже)
    volumes:
      - ./nats/data:/data
